# Config file for automatic testing at travis-ci.org
language: python
sudo: false

python:
  - 3.8
  - 3.7
  - 3.6
  - "pypy3"

# command to install dependencies
install: pip install -r requirements.txt

# lint before running tests
before_script: flake8 pvl tests

# command to run tests
script: py.test tests
