channels:
  - conda-forge
  - defaults
dependencies:
  - bump2version
  - cookiecutter
  - flake8
  - pytest
  - pytest-cov
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-apidoc
  - sphinxcontrib-autoprogram
  - twine
# These are optional dependencies, and pvl should pass all its tests without them.
  - python-dateutil
  - astropy
  - pint
  - multidict
