# This workflow is purely to determine code coverage.
# Since we really only need to run coverage once (not N times for every combination
# in a test matrix), there is some duplication with the primary testing workflow.

name: Code Coverage

on: [push, pull_request]

env:
  python-version: 3.7

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install pytest-cov
    - name: Install pvl
      run: python -m pip install -e .
    - name: Test with pytest and generate coverage report
      run: pytest --cov=./pvl --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
